
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "W:/Apps/JETBRAINS/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
